version: '3'

services:
  server:
    build: .
    volumes:
      - ./server:/home/node/server
      - /home/node/server/node_modules
    ports:
      - '4002:4002'
      - '4005:4005'
    stdin_open: true
    tty: true
  client:
    build: .
    volumes:
      - ./client:/home/node/client
      - /home/node/client/node_modules
    ports:
      - '3002:3002'
      - '3003:3003'
    stdin_open: true
    tty: true
