version: '3'

services:
  server:
    build: .
    volumes:
      - ./server:/home/node/server
      - /home/node/server/node_modules
    ports:
      - '3333:3333'
    stdin_open: true
    tty: true
  client:
    build: .
    volumes:
      - ./client:/home/node/client
      - /home/node/client/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
