[build]
  environment = { NODE_VERSION = "12", AWS_LAMBDA_JS_RUNTIME = "nodejs12.x" }
  base = "client"
  command = "yarn generate"
  publish = "client/dist"
  functions = "client/functions"

[dev]
  command = "yarn start"
