[build]
  environment = { NODE_VERSION = "14", AWS_LAMBDA_JS_RUNTIME = "nodejs14.x" }

[dev]
  base = "client"
  command = "yarn start"
  publish = "client/dist"
  functions = "client/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
